"""Create Game Model

Revision ID: ab920bc4d060
Revises: e978dc654185
Create Date: 2023-12-08 14:45:08.099515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab920bc4d060'
down_revision = 'e978dc654185'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(), nullable=True))
        batch_op.drop_column('platforn')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platforn', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
